[package]
name = "openvm-rv32im-integration-tests"
description = "Integration tests for the OpenVM rv32im extension"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm-instructions = { workspace = true }
openvm-stark-sdk.workspace = true
openvm-circuit = { workspace = true, features = ["test-utils"] }
openvm-transpiler.workspace = true
openvm-rv32im-circuit.workspace = true
openvm-rv32im-guest.workspace = true
openvm-rv32im-transpiler.workspace = true
openvm = { workspace = true }
openvm-toolchain-tests = { path = "../../../crates/toolchain/tests" }
eyre.workspace = true
test-case.workspace = true
serde = { workspace = true, features = ["alloc"] }
strum.workspace = true

[dev-dependencies]
openvm-sdk = { path = "../../../crates/sdk", features = ["test-utils"] }
rrs-lib = { workspace = true }

[features]
default = ["parallel"]
parallel = ["openvm-circuit/parallel"]
tco = ["openvm-rv32im-circuit/tco"]
aot = ["openvm-rv32im-circuit/aot"]
cuda = ["openvm-rv32im-circuit/cuda"]
